---
abstract: 'block header injections in responses'
author:
  - 'Robert Rothenberg, C<< <rrwo at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  HTTP::Request: 0
  Plack::Builder: 0
  Plack::Request: 0
  Plack::Response: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-BlockHeaderInjection
no_index:
  directory:
    - inc
    - t
requires:
  Plack::Middleware: 0
  Plack::Util: 0
  Plack::Util::Accessor: 0
  perl: 5.01
  version: 0.77
resources:
  bugtracker: https://github.com/robrwo/Plack-Middleware-BlockHeaderInjection/issues
  homepage: http://rrwo.tumblr.com
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/robrwo/Plack-Middleware-BlockHeaderInjection.git
version: 0.001000
